Api\FileBundle\Model\PhotoUpload:
    properties:
        type:
            - NotBlank: ~
            - Choice: { choices: [avatar, post]}
        file:
            - File:
                maxSize: 14k
                mimeTypes: [image/jpg, image/png]
