fos_rest:
    param_fetcher_listener: true
    view:
        view_response_listener: force
        formats:
            xml: true
            json: true
        templating_formats:
            html: true
        failed_validation: HTTP_BAD_REQUEST
    format_listener:
        rules:
            - { path: '^/api', priorities: [ json, xml ], fallback_format: ~, prefer_extension: true }
            - { path: '^/', priorities:['text/html', '*.*'], fallback_format: html, prefer_extension:true }
    body_listener: true
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
    allowed_methods_listener: true
    access_denied_listener:
        json: true

sensio_framework_extra:
    view: { annotations: false }
    router: { annotations: true }