biz_web:
    resource: "@BizWebBundle/Resources/config/routing.yml"
    prefix:   /

api_user:
    resource: "@BizApiBundle/Resources/config/routing.yml"
    prefix:   /api
    type:     rest

nelmio_apidoc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /v3/doc

