web_site:
    resource: "@WebSiteBundle/Resources/config/routing.yml"
    prefix:   /

api_blog:
    resource: "@ApiBlogBundle/Resources/config/routing.yml"
    prefix:   /api

lef_user:
    resource: "@LefUserBundle/Resources/config/routing.yml"
    prefix:   /
    type:     rest

nelmio_apidoc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /v3/doc

