security:
    encoders:
        Dat\UserBundle\Entity\User:
            algorithm: sha512

    providers:
        main:
            entity: { class: DatUserBundle:User, property: mobile }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: /.*
            form_login:
                check_path: /login_check
                login_path: /login
            logout: true
            security: true
            anonymous: ~

    access_control: ~
