parameters:
#    dat_blog.example.class: Dat\BlogBundle\Example

services:
#    dat_blog.example:
#        class: %dat_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
