parameters:
#    dat_file.example.class: Dat\FileBundle\Example

services:
#    dat_file.example:
#        class: %dat_file.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
