parameters:
    biz_api.user.class: Dat\UserBundle\Entity\User
    biz_api.user_handler.class: Biz\ApiBundle\Handler\UserHandler
    biz_api.user_profile.class: Dat\UserBundle\Entity\Profile
    biz_api.user_profile_handler.class: Biz\ApiBundle\Handler\UserProfileHandler

services:
    biz_api.user_handler:
        class: %biz_api.user_handler.class%
        arguments: [@doctrine.orm.lefuser_entity_manager, %biz_api.user.class%, @form.factory, @security.encoder_factory]
    biz_api.user_profile_handler:
        class: %biz_api.user_profile_handler.class%
        arguments: [@doctrine.orm.lefuser_entity_manager, %biz_api.user_profile.class%, @form.factory]
