Dat\UserBundle\Entity\User:
    properties:
        username:
            - NotBlank: ~
            - Length:
                min: 2
                max: 50
        mobile:
            - NotBlank: ~
            - Regex:
                pattern: "/^1\d{10}$/"
                match: true
                message: "Your mobile is not validate"
        password:
            - NotBlank: ~
            - Length:
                min: 6
                max: 20