parameters:
    lef_user.user.class: Lef\UserBundle\Entity\User
    lef_user.user.handler.class: Lef\UserBundle\Handler\UserHandler
    lef_user.profile.class: Lef\UserBundle\Entity\Profile
    lef_user.profile.handler.class: Lef\UserBundle\Handler\ProfileHandler
    lef_user.photo.class: Lef\UserBundle\Entity\Photo
    lef_user.photo.handler.class: Lef\UserBundle\Handler\PhotoHandler

services:
    lef_user.user.handler:
        class: %lef_user.user.handler.class%
        arguments: [ @doctrine.orm.lefuser_entity_manager, %lef_user.user.class%, @security.encoder_factory, @form.factory ]
    lef_user.profile.handler:
        class: %lef_user.profile.handler.class%
        arguments: [ @doctrine.orm.lefuser_entity_manager, @form.factory, %lef_user.profile.class% ]
    lef_user.photo.handler:
        class: %lef_user.photo.handler.class%
        arguments: [ @doctrine.orm.lefuser_entity_manager, @form.factory, %lef_user.photo.class% ]