Lef\UserBundle\Entity\User:
    properties:
        username:
            - NotBlank: ~
            - NotNull: ~
            - Length:
                min: 2
                max: 50
                minMessage: "Your username must be at least characters length"
                maxMessage: "Your username cannot be longer than characters length"
        mobile:
            - Regex:
                pattern: "/^1\d{10}$/"
                match: true
                message: "Your mobile is not validate"
        password:
            - NotBlank: ~
            - NotNull: ~
            - Length:
                min: 6
                max: 20
                minMessage: "Your password must be at least characters length"
                maxMessage: "Your password cannot be longer than characters length"

Lef\UserBundle\Entity\Profile:
    properties:
        gender:
            - Choice: { choices: [ male, female ], message: "选择一个准确的性别" }

Lef\UserBundle\Entity\Photo:
    properties:
        file:
            - File:
                maxSize: 6000000