parameters:
#    api_user.example.class: Api\UserBundle\Example

services:
#    api_user.example:
#        class: %api_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
