parameters:
#    web_site.example.class: Web\SiteBundle\Example

services:
#    web_site.example:
#        class: %web_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
