parameters:
#    api_blog.example.class: Api\BlogBundle\Example

services:
#    api_blog.example:
#        class: %api_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
